server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huage969030970/springcloud-config.git #GitHub上面的git仓库名字
          ####搜索目录
          search-paths:
            - springcloud-config
          #username: 969030970@qq.com
          #password: mm18775716120
          #force-pull: true
      ####读取分支
      label: master
      #name: 服务名
      #profiles: 环境(dev/test/prod)

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest


management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'